# Generated by Django 5.0.3 on 2024-03-10 09:49

import django.forms.widgets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclarify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(verbose_name=django.forms.widgets.Textarea),
        ),
    ]
