# Generated by Django 5.0.3 on 2024-03-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclarify', '0002_alter_codesnippet_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('test_cases', models.TextField()),
                ('solution', models.TextField()),
                ('Difficulty', models.TextField()),
            ],
        ),
    ]
