# Generated by Django 5.0.3 on 2024-03-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclarify', '0005_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='Difficulty',
            new_name='difficulty',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='codeclarify.problem'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(),
        ),
    ]
