# Generated by Django 5.0.3 on 2024-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclarify', '0007_submission_date_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
