# Generated by Django 5.0.3 on 2024-03-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclarify', '0008_alter_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='codeclarify.problem'),
        ),
    ]
