# Generated by Django 5.0.3 on 2024-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclarify', '0009_alter_testcase_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraint',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
