# Generated by Django 5.0.3 on 2024-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclarify', '0011_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
