# Generated by Django 5.0.3 on 2024-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeclarify', '0012_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Compile Error', 'Compile Error')], max_length=20),
        ),
    ]
